### ISSUE TITLE
Mod doesnt seem to function

### ISSUE THREAD

**Issue by Drew223** [Albeoris/Memoria.DisciplesLiberation#2]
Hey there Albeoris,
I don't know whether it's due to a game update or a BepinEx update but the mod no longer seems to be functioning in game.
Hope you can help!
Drew223

**Comment by Albeoris** [comment]
@Drew223, I just checked it. Everything works fine (Steam Version).
Try to remove BeepInEx folder and install it again.
Don't forget about BeepInEx. Don't forget to configure it again after the first run.
